<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\InventorySetupRepository;
use App\Entities\InventorySetup;
use App\Validators\InventorySetupValidator;

/**
 * Class InventorySetupRepositoryEloquent
 * @package namespace App\Repositories;
 */
class InventorySetupRepositoryEloquent extends BaseRepository implements InventorySetupRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return InventorySetup::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }


    public function validator()
    {
        return parent::validator(); // TODO: Change the autogenerated stub
    }
}
