<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\RequisitionDetailRepository;
use App\Entities\RequisitionDetail;
use App\Validators\RequisitionDetailValidator;;

/**
 * Class RequisitionDetailRepositoryEloquent
 * @package namespace App\Repositories;
 */
class RequisitionDetailRepositoryEloquent extends BaseRepository implements RequisitionDetailRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return RequisitionDetail::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function validator()
    {
        return parent::validator(); // TODO: Change the autogenerated stub
    }
}
