<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\WelfareItemRepository;
use App\Entities\WelfareItem;
use App\Validators\WelfareItemValidator;

/**
 * Class WelfareItemRepositoryEloquent
 * @package namespace App\Repositories;
 */
class WelfareItemRepositoryEloquent extends BaseRepository implements WelfareItemRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return WelfareItem::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function validator()
    {
        return parent::validator(); // TODO: Change the autogenerated stub
    }
}
